# Use the latest Ubuntu image as the base
FROM ubuntu:latest

# Update APT package lists
RUN apt-get update

# Upgrade installed packages
RUN apt-get upgrade -y

# Create a simple command to echo "Hello, World!" when the container is run
CMD echo "Hello, World!"
